spring:
  application:
    name: hello-spring-boot
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 9090
  servlet:
    context-path: /boot
